### ISSUE TITLE
I cant use it

### ISSUE THREAD

**Issue by TedTheSlayer** [Cracked-Domerrist/Tupperbox-Image-and-Command-Grabber#1]
I dont have enough tuppers for this to be useful

**Comment by Cracked-Domerrist** [comment]
Can you provide logs for this? I would be happy to help you!

**Comment by TedTheSlayer** [comment]
[logs.txt](https://github.com/Cracked-Domerrist/Tupperbox-Image-and-Command-Grabber/files/11714007/logs.txt)

**Comment by Cracked-Domerrist** [comment]
It appears your logs are empty, TedTheSlayer, could you provide screenshots of the commandline, the folder directory, and the actual tuppers.json file from your tupperbox?

**Comment by TedTheSlayer** [comment]
No
