### ISSUE TITLE
progam closes when grabbing images

### ISSUE THREAD

**Issue by Kaiffcyan** [Cracked-Domerrist/Tupperbox-Image-and-Command-Grabber#2]
The progam closes everytime i run the progam when grabbing image from my tupper, it managed to grab one image but it wasn't able to grab more and just closed the program

**Comment by Cracked-Domerrist** [comment]
Crazy, seems I must've forgotten to have the program wait for an input before stopping. I'll release an update--check the main page! It should be under Verison 1.0.1

**Comment by Kaiffcyan** [comment]
didn't work the program still closes when getting only one image

**Comment by Cracked-Domerrist** [comment]
Can you send me the tuppers.json file to me? I'll work on it as best I can.

**Comment by Cracked-Domerrist** [comment]
There's a new patch coming out, thank you for adding your issues! Please tell me if your issue has been resolved.

**Comment by Kaiffcyan** [comment]
it's fix! glad it is working now
